### ISSUE TITLE
GDMO not opening on tab after first launch

### ISSUE THREAD

**Issue by NumbersTada** [maxnut/GDmenu#121]
bruh
after first launch, gdmo just doesnt open when i press tab. the mods i enabled still work though

**Comment by Mar1Xd** [comment]
> bruh after first launch, gdmo just doesnt open when i press tab. the mods i enabled still work though

I had the same problem,so I deleted the gdmo files and now I can't redownload it.It worked for the first launch and then when I woke up tomorrow it didn't work.

**Comment by Blackberrycak3** [comment]
same problem bro i have no idea why

**Comment by KrazyFF** [comment]
i had a problem that might be similar - when i pressed tab after reopening the game basically all would be gone except for like 1 tab which would be at the bottom, i think i fixed this though and it might be because your game is not running at 1080p (1920x1080) so to fix it you are gonna wanna go to the GDMO folder, then go to windows.json, scroll down to res and change it to your monitor's resolution, mine is 1440p for example. I've reopened the game multiple times and the issues haven't persisted.

**Comment by Blackberrycak3** [comment]
Well my monitor is 1920x1080 and it works now  Sent from Mail for Windows From: KrazyFFSent: Wednesday, January 10, 2024 7:47 AMTo: maxnut/GDMegaOverlayCc: Blackberrycak3; CommentSubject: Re: [maxnut/GDMegaOverlay] GDMO not opening on tab after first launch (Issue #121) i had a problem that might be similar - when i pressed tab after reopening the game basically all would be gone except for like 1 tab which would be at the bottom, i think i fixed this though and it might be because your game is not running at 1080p (1920x1080) so to fix it you are gonna wanna go to the GDMO folder, then go to windows.json, scroll down to res and change it to your monitor's resolution, mine is 1440p for example. I've reopened the game multiple times and the issues haven't persisted.—Reply to this email directly, view it on GitHub, or unsubscribe.You are receiving this because you commented.Message ID: ***@***.***>

**Comment by hexaveiii** [comment]
Same issue happened with me. Just try to restart and if that doesn't work verify integrity of files on steam and retry the download process of the menu.

**Comment by MysticAx0lotl** [comment]
GDMO doesn't support 2.203 and 2.204, roll back to 2.202/2.201 or wait for an update
