### ISSUE TITLE
Compiling code instractions

### ISSUE THREAD

**Issue by TV46** [maxnut/GDmenu#183]
I was just hoping you could add some simple instructions on how to compile code in the read me just so people who are having problems with anti-virus can compile the code for themselves, thanks :)

**Comment by RevolvingMadness** [comment]
Agreed

**Comment by MysticAx0lotl** [comment]
Theoretically building from source will still give you the same antivirus issues, since the resulting program exhibits the same behavior. If you need to know how to add exceptions to Windows Defender, [microsoft has a tutorial](https://support.microsoft.com/en-us/windows/add-an-exclusion-to-windows-security-811816c0-4dfd-af4a-47e4-c301afe13b26)

Please note that the current release does not currently support 2.204

**Comment by RevolvingMadness** [comment]
Does building from source give you 2.204 support?

**Comment by MysticAx0lotl** [comment]
Yes, however it is still extremely unstable. It's recommended to wait for a proper release

If you want to try it anyway, I recommend you ask in the [discord server](https://discord.gg/eYWUpYcPhX) for assistance on building from source

**Comment by Stronkkey** [comment]
You can use github actions (in the "Actions" tab near the issues button) if you want to grab a dll from a specific commit.

**Comment by Stronkkey** [comment]
@MysticAx0lotl I don't think that solves their issue. They want to build the project from the source and might not want the dll from the actions (actions require merging which is bad if you can't test if your code even works).

**Comment by MysticAx0lotl** [comment]
Fair, I'll reopen it
